INSERT INTO books (id, category, title, author, total_copies, available_copies) VALUES
(gen_random_uuid(), 'Agama', '100 Pesan Nabi untuk Wanita', 'Badwi Mahmud Al-Syaikh', 1, 1),
(gen_random_uuid(), 'Agama', '199 Kebiasaan yang Keliru', 'Fatchul Mubin Hamid', 1, 1),
(gen_random_uuid(), 'Agama', '22 Masalah Agama', 'H.A. Aziz Salim Basyarahil', 1, 1),
(gen_random_uuid(), 'Agama', '99 Kisah Asmaul Husna', 'Ahmad R Islami', 1, 1),
(gen_random_uuid(), 'Agama', 'Agar Selalu Ditolong Allah', 'Hendra Setiawan', 1, 1),
(gen_random_uuid(), 'Agama', 'Aku Bisa Mengerjakan Wudhu', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Agama', 'Al Islam', 'Teungku Muhammad Hasbi Ash Shiddieqy', 2, 2),
(gen_random_uuid(), 'Agama', 'Al-Matsurat Wazhifah Kubra', 'Imam Asy-Syahid Hasan Al-Banna', 1, 1),
(gen_random_uuid(), 'Agama', 'Allah Tuhanku , Islam Agamaku', 'Rein Nur azizah', 2, 2),
(gen_random_uuid(), 'Agama', 'Ampunan Allah', 'Nurul Huda, S. Ag.', 1, 1),
(gen_random_uuid(), 'Agama', 'Belajar Sukses dari Shalat', 'K.H. Muhammad Rusli Amin, MA', 1, 1),
(gen_random_uuid(), 'Agama', 'Bening Hati', 'K.H Abdullah Gymnastiar, Bahsyar Isra', 1, 1),
(gen_random_uuid(), 'Agama', 'Berani Jujur', 'Ibrahim Fattah', 1, 1),
(gen_random_uuid(), 'Agama', 'Berbakti kepada Orang Tua', 'Aqila Tazkia', 1, 1),
(gen_random_uuid(), 'Agama', 'Buku Iqro', 'K.H. As''ad HUmam', 1, 1),
(gen_random_uuid(), 'Agama', 'Buku Pertamaku Wudhu Shalat & Doa', 'Ust. M. Hamzah', 1, 1),
(gen_random_uuid(), 'Agama', 'Cinta Kebersihan', 'Sahal Fikri', 1, 1),
(gen_random_uuid(), 'Agama', 'Dan Muhammad adalah Utusan Allah', 'Annemarie Schimmel', 1, 1),
(gen_random_uuid(), 'Agama', 'Dahsyatnya Doa Ibu', 'Ust. Syamsuddin Noor', 2, 2),
(gen_random_uuid(), 'Agama', 'Dear Allah, Jadikan Aku Muslimah Salehah', '@nasihatku', 1, 1),
(gen_random_uuid(), 'Agama', 'Dear Allah, Tuntun Aku ke Jalan-Mu', '@nasihatku', 1, 1),
(gen_random_uuid(), 'Agama', 'Detik-Detik Menjelang Ajal', 'Khalid bin Abdurrahman As-syayi', 1, 1),
(gen_random_uuid(), 'Agama', 'Di Atas Sajadah Cinta', 'Habiburrahman El Shirazy', 1, 1),
(gen_random_uuid(), 'Agama', 'Dzikir Pagi & Petang dan Sesudah Shalat Fardhu', 'Syaikh Sa''id bin Ali bin Wahf al-Qahthani', 1, 1),
(gen_random_uuid(), 'Agama', 'Fattabiuni Ikuti Sunnahku: Gaul Cara Nabi SAW', 'Muhammad bin Abdurrahman', 1, 1),
(gen_random_uuid(), 'Agama', 'Istighfar', 'Ibnu Tamiyah', 1, 1),
(gen_random_uuid(), 'Agama', 'Juz Amma', 'Ust. Abdurahman', 4, 4),
(gen_random_uuid(), 'Agama', 'Kenali Dirimu, Temukan Tujuan Hidupmu', 'Royhan Firdausy', 1, 1),
(gen_random_uuid(), 'Agama', 'Komik 100 Kebiasaan Nabi', 'Wawan Kungkang, Straightedge Dw', 1, 1),
(gen_random_uuid(), 'Agama', 'Kuberserah', 'Prof. Dr. H.M. Amin Syukur, M.A.', 1, 1),
(gen_random_uuid(), 'Agama', 'Kumpulan Doa Anak Sholeh', 'Indah Sari', 1, 1),
(gen_random_uuid(), 'Agama', 'Malang Nian Orang yang Tidak Sholat', 'Muhammad Abdul Malik Az-zagabhi', 1, 1),
(gen_random_uuid(), 'Agama', 'Memakmurkan Masjid', 'Tiara Arum', 1, 1),
(gen_random_uuid(), 'Agama', 'Memberi Maaf', 'Sahal Fikri', 1, 1),
(gen_random_uuid(), 'Agama', 'Menajamkan Otak Dengan Shalat', 'M. Syafii Masykur', 1, 1),
(gen_random_uuid(), 'Agama', 'Menangis Karena Allah', 'Mansur Abdul Hakim', 1, 1),
(gen_random_uuid(), 'Agama', 'Meneladani Rasul', 'Aqila Tazkia', 1, 1),
(gen_random_uuid(), 'Agama', 'Meneladani Shalat & Wudhu Nabi', 'Syaikh Abdullah b. Abdurrahman al-Jibrin', 1, 1),
(gen_random_uuid(), 'Agama', 'Menepati Janji', 'Sahal Fikri', 1, 1),
(gen_random_uuid(), 'Agama', 'Menghormati yang Lebih Tua', 'Tiara Arum', 1, 1),
(gen_random_uuid(), 'Agama', 'Menjadi Wanita Terbaik: 40 Hadits Tentang Wanita', 'Naseeha', 1, 1),
(gen_random_uuid(), 'Agama', 'Menutup Aurat', 'Tiara Arum', 1, 1),
(gen_random_uuid(), 'Agama', 'Menzikirkan Mata Hati', 'Muhammad Arifin Ilham', 1, 1),
(gen_random_uuid(), 'Agama', 'Meraih Bening Hati dengan Manajemen Qolbu', 'K.H Abdullah Gymnastiar', 1, 1),
(gen_random_uuid(), 'Agama', 'Panduan Lengkap Ibadah Menurut Al-Quran, As-Sunnah, dan
Pendapat Para Ulama', 'Muhammad Bagir', 1, 1),
(gen_random_uuid(), 'Agama', 'Pemimpin Istimewa ala Rasulullah', 'Imam Nawawi', 1, 1),
(gen_random_uuid(), 'Agama', 'Pintar Belajar Sholat & Berdoa Disertai Juz Amma', 'Nur Iman', 1, 1),
(gen_random_uuid(), 'Agama', 'Risalah Kekuatan Jiwa', 'Ashad Kusuma Jaya', 1, 1),
(gen_random_uuid(), 'Agama', 'Risalah Tuntunan Shalat Lengkap', 'Drs. Moh. Rifa''i', 1, 1),
(gen_random_uuid(), 'Agama', 'Santun Berbicara', 'Anisa Septiana', 1, 1),
(gen_random_uuid(), 'Agama', 'Satu Tiket ke Surga', 'Zabrina A. Bakar', 1, 1),
(gen_random_uuid(), 'Agama', 'Satu Tiket ke Surga 2', 'Zabrina A. Bakar', 1, 1),
(gen_random_uuid(), 'Agama', 'Sayangi Binatang', 'Aqila Tazkia', 1, 1),
(gen_random_uuid(), 'Agama', 'Sayangi Saudara', 'Anisa Septiana', 1, 1),
(gen_random_uuid(), 'Agama', 'Selalu Berdoa', 'Tiara Arum', 1, 1),
(gen_random_uuid(), 'Agama', 'Semangat Belajar', 'Anisa Septiana', 1, 1),
(gen_random_uuid(), 'Agama', 'Sifat Shalat Nabi SAW', 'Syaikh Muhammad bin Shalih Utsamain', 1, 1),
(gen_random_uuid(), 'Agama', 'Suka Berbagi', 'Ibrahim Fattah', 1, 1),
(gen_random_uuid(), 'Agama', 'Suka Menolong', 'Tiara Arum', 1, 1),
(gen_random_uuid(), 'Agama', 'Sukses Dunia Akhirat', 'Nurul Huda, S. Ag.', 1, 1),
(gen_random_uuid(), 'Agama', 'Tuntutan Shalat Lengkap', 'Sandro Jaya Jakarta', 1, 1),
(gen_random_uuid(), 'Agama', 'Ucap Salam dan Minta Izin', 'Sahal Fikri', 1, 1),
(gen_random_uuid(), 'Agama', 'Ziarah Hati', 'Fika Faila Sufa, dll.', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'A Concert at Springvale', 'May Gan', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'A Gift for Mom', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'A Long Journey', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'A Magic Box', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'A Photo Album of Grandfather', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'A Picture', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'A Seed', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'A World Without Pollution', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Animal Farm', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Animal Opposites', 'Aligator Publsihing', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Baby First: Animal', 'Hinklers', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Ball Games', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Bedtime', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Best Friends', 'Cynthia Stierle', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Big and Small', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Birthday Gift', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Bob''s Summer Holiday', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Busy Bonnie', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Buying shoes', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Cities', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Clean my room', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Colorful Seasons', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Costume Party', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Dan the Ant', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Day and Night', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Different jobs', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Disney Aladdin: The Cave of Wonders', 'Tim Penerbit Pelangi Sdn', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Don''t Open the Door', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Draw A Picture', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Dream Job', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Ear Song', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Eat Up All The Food', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Emotions', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'English Worksheet', 'Alison Koh, M.A, Dipl. Ed.', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Farm', 'Yoyo Books', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Fat and Thin', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Flowers', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Foolish Bear', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Four Seasons', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Fruit Party', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Fun at The Mall', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Go Fishing', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Go To The Zoo', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Good Morning', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Greedy Lion', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Greek and Fran', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Green Montessori School', 'Green Montesori School', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Happy New Year', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Have A Good Dream', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Help!', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Helping Flood Victims', 'ELP', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Hot Summer!', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'How Can I Find The Milk?', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'I Can Count', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'I Can Fly', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'I Can Walk', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'I Get It!', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'I Have An Idea', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'I''m The King', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'I''m Tyranosaurus', 'Jean Marzollo', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'I''m Very Happy', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'In Winter', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'It''s A Well Fitting Dress', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Jenny''s Week', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Jimmy is Hungry', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Kate''s Cake', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Kitty''s basket', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Know Your Opposites', 'Alka Publications', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Learn To Fly', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Learning Together Nursery 8', 'Penerbit Child Educational Co', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Little Judy', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Little Miss Birthday', 'Koger Hargreaves', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Little Miss Shy and The Fairy Godmother', 'Koger Hargreaves', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Little Pilot', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Long and Short', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Lucky or Unlucky', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Make A Salad', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Merry Christmas', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Monster Castle', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Movie Theatre Storybook & Movie Projector', 'Nickledeon', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Music Party', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'My ABC Mini Library', 'Disney', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'My Dog Can''t Read', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'My English Activity Workbook 1', 'Scroll Children Educational Activity', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'My English Activity Workbook 2', 'Scroll Children Educational Activity', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'My English Activity Workbook 4', 'Scroll Children Educational Activity', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'My Family', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'My First Vegetable Book', 'Tim Penulis BIP', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'My First Words', 'Autumn Publishing', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'My First Number Book', 'Tim Penulis BIP', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'My Mother', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'My Pet', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'My School Bag', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'New Clothes', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'No, Thanks', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Pat Cat and Tat Rat', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Peppa Plays Football', 'Tim Penerbit Ladybird', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Pets', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Postman Past Picnic', 'Tien Wah Press', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Protect The Eyes', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Rainy Day', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Rin Get Meg''s Pin', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Robot Roy', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Roy Going To Town', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Save The Water', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Shapes', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Shoes', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Shopping', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Speliing Sun', 'John Ariel,', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Sports Meet', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Stan The Stag', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Tableware', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Teddy Bear', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Teddy Bear', 'Priddy Books', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'The Best Thing', 'Disney', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'The Blue Ocean', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'The Fox and The Crow', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'The King''s Ring', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'The Lantern Festival', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'The Lost Mice', 'Disney', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'The Lost Shape', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'The Sea', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'There''s A Monster', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Time For A Bath', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'To See A Doctor', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Tom Wants To Be A Chef', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Tommy The Indian', 'Modern Publishing Group', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Toys', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Traffic Light', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Travel with Mr. Wind', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Vegetables', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'We Walk Together', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Weather', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Weekend', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Welcome To My Home', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Well Done', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'What Are You Doing?', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'What Color', 'Anthea Sieveking', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'What''s In The Box?', 'Jiangxi Education Publishing House', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Where Is Your Bag, Elsa?', 'Jiangxi Education Publishing House', 2, 2),
(gen_random_uuid(), 'Bahasa Inggris', 'Where Is Spot?', 'Eric Hill', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Wibbly Pi''s Silly', 'Madaboutbooks', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Yes English for Children 2', 'Drs. Ahmad Izzan, M.Ag, & Dra. Hj. Entin, Dipl
TESL', 1, 1),
(gen_random_uuid(), 'Bahasa Inggris', 'Zags Pet', 'Si Yiah Ling', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', '100 Dongeng Bikin Ceria', 'Endang Firdaus', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Abu Bakar Ash Shidiq yang Baik Hati', 'Ulfah H.T', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Ada Monster Taman Kanak-Kanak', 'Zhou Soulan', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Anak Santun: Bintang Ke Kebun Binantang', 'Lia Herliana', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Berani ke Dokter', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Bilang Alhamdulillah', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Bilang Bismillah', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Bilang Masya Allah', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Bilang Subhanallah', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Bilang Terimakasih', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Bisa Baca Al Quran', 'Luthfi Yansyah', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Bisa Berhitung', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Bisa Makan Sendiri', 'Yenny S Firdaus', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Bisa Pakai Baju Sendiri', 'Lia Herliana', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Cantik Memakai Hijab', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Cinta Allah', 'Alwi Alatas', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Rajin Membantu Ibu', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Sayang Anak Yatim Piatu', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Sayang Ayah & Ibu', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Sayang Keluarga', 'dr. Rina Raflesia, M.A', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Senang Berbagi', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Senang Mengaji', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Senang Menjaga Adik', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Suka Menabung', 'Yenny S. Firdaus', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Tidak Bertengkar', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Tidak Menangis Lagi', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Tidak Ngompol', 'Yenny S. Firdaus', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Aku Tidak Suka Berbohong', 'Leni Aryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Ali Kecil Mengenal Islam', 'Ulfah H.T', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Always Together', 'Lulu', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Anjing Kecil', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Asal Mula Daging Gajah', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Asal Mula Danau Toba', 'MB Rahimsyah AR', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Ayo Kita Berteman: Perbedaan itu Menyenangkan', 'Ana B. Itsna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Barbie Maripossa & The Fairy Princess', 'Tim Penulis Gramedia', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Bawang Merah dan Bawang Putih', 'Filyah & Ghibran', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Bebek dan Burung hantu', 'Dhany Larito', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Berani Berbeda', 'Benny Rhamdani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Berteman Itu Indah', 'Leyla', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Buaya yang Serakah', 'Iin Indarti', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Bunga Rampai: Dongeng dan Cerita Dunia', 'Arbi Syahputra', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Legenda Sangkuriang & Lutung Kasarung', 'Puput Mugiyati', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Rakyat 33 Provinsi', 'Yustia Angelia', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Rakyat Nusantara: Janji Raja yang Biajksana', 'Imam KR Moncol', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Rakyat Nusantara: Legenda Bersejarah dari Sabang
sampai Merauke', 'Kak Nung', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Aku Anak Bertanggung Jawab', 'Rian F. Rahman', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Aku Anak Jujur', 'Rian F. Rahman', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Aku Cinta Kebersihan', 'Rian F. Rahman', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Aku Gemar Menabung', 'Rian F. Rahman', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Tema 1: Diri Sendiri, Aku dan Kesukaanku', 'Rian F. Rahman', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Tema 2: Aku Sayang Keluargaku', 'Rian F. Rahman', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Tema 3: Aku dan Lingkunganku', 'Rian F. Rahman', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Tema 4: Binatang: Aku Sayang Binatang', 'Rian F. Rahman', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Tema 5: Tanaman: Aku Sayang Tanaman', 'Rian F. Rahman', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Tema 6: Kendaraan: Aku dan Kendaraan', 'Rian F. Rahman', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Tema 7: Alam Semesata: Aku dan Alam Semesta', 'Rian F. Rahman', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Cerita Tematik: Tema 8: Negaraku: Aku Cinta Negaraku', 'Rian F. Rahman', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Derita Lalat', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Dongeng Anak Pilihan', 'Benny Rhamdani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Dongeng Bergambar Si Kancil yang Cerdik', 'Ghibran Ar-Rosyid', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Dongeng Binatang', 'Yudhistira Ikranegara', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Dongeng Sedunia', 'Esther S. Mandjani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Dongeng Seru Flora', 'Mauline D. Agnesia', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'D''Silver Rainbow', 'Nuha', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Flory & Komidi Putar', 'Nunik Utami', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Flowerist: Petualangan di Dunia Mimpi', 'Sarah Alya', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Gading Gajah', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Gruffalo: Apa itu Gruffalo?', 'Julia Donaldson & Axel Scheffler', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Hadiah Untuk Dhea', 'Jihan', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Halo Balita: Kisah dalam Al-Quran - Buah Tsur', 'Indrayani Mallo', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Halo Balita: Penuntun Aku Senang Berdoa', 'Benny Rhamdani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kambing dan Ikan Mas', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kancil dan Harimau', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kancil Yang Cerdik', 'MB Rahimsyah AR', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kecerdikan Menumbuhkan Kebaikan', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kecerdikan Sang Kancil', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Keledai Yang Cerdik', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kera dan Buaya Penipu', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kesabaran Ulat Bulu', 'Dhany', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Khalid bin Walid: Sang Pedang Allah', 'Ulfah H.T', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kiki Mencari Keluarga Baru', 'Iwok Abqori', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kisah 1001 Malam Abu Nawas', 'Ghibran Maulana', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kisah Anak Gembala', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kisah Anak Tikus', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kisah Bawang Merah dan Bawang Putih', 'Yudhistira Ikranegara', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kisah Bergambar 25 Nabi dan Rasul', 'Maulana Ghibran', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kisah Legenda Malin Kundang', 'Filyah & Ghibran', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kisah Teladan Anak Muslim', 'Filyah & Ghibran', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Koleksi Dongeng Dunia Binatang', 'Lani Putri', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Komik Sedekah', 'Arif Abinaufal', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Kura-kura Sang Juara', 'Dhany', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Landi Landak yang Kesepian', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Legenda Keong Emas', 'Yudhistira Ikranegara', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Lihat Gigiku Sehat dan Kuat', 'Marie Urbankova', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Little Celebrity', 'Hanifah Nurul Auliya', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Menonton Film Bersama', 'Nicklodeon', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Misteri Monster Rawa', 'Salma', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'My Persian Rainbow', 'Kirana', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Nasehat Katak', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Nyai Roro Kidul', 'HAR', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Pangeran Kamil: Belajar Adab Toilet', 'Canun Kamil & Fufu Elmart', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Para Detektif Mungil', 'Cressida Cowell', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Pelukis Misterius', 'Gung Putru', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Penyesalan Anak Katak', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Penyesalan Kerbau', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Pertolongan Kakak Tua', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Petaka Tanduk Rusa', 'Dhany', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Petualangan Anak Anjing Super Seru', 'Devin Ann Wooster', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Petualangan Ayam dan Anjing', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Petualangan Sisi', 'Pratami Diah Herliani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Pinkalicious: Cerita Bagi Kamu Penyuka Pink', 'Victoria Kann & Elizabeth Kann', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Pop Science for Children: Baby Animals - Burung', 'Bayu & Ikhsan Ican', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Pop Science for Children: Baby Animals - Ikan, Amfibi, Hewan
Melata', 'Bayu & Ikhsan Ican', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Rindu Purnama', 'Ayunda', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Sa''ad bin Abi Waqash: Pemanah yang Hebat', 'Randhy Cahya', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Semut', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Semut dan Kepompong', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Semut dan Lebah', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Akhlak Mulia: Anti Korupsi', 'Sudianto', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Akhlak Mulia: Berdoa', 'Sri Widiastuti', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Akhlak Mulia: Beribadah', 'Irma Irawati', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Akhlak Mulia: Bertakwa', 'Aira Kimberly', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Akhlak Mulia: Mengantri', 'Ellvira Suryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Akhlak Mulia: Menolong Teman', 'Miyosi Margib Utami', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Akhlak Mulia: Patuh Lalu Lintas', 'Sudianto', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Akhlak Mulia: Perasaanku', 'Tuti Sitanggang', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Akhlak Mulia: Taat Pajak', 'Elvira Suryani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Ande-Ande Lumut', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Batu Menangis', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Jaka Tarub', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Joko Kendil', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Kebo Iwa', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Keong Emas', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Legenda Danau Toba', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Malin Kundang', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Putri Duyung', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Sangkuriang', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Si Pahit Lidah', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Si Pitung', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat: Timun Mas', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat Nusantara: Ikan Patin', 'Iman KR Moncol', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat Nusantara: Putri Pandan Berduri', 'Iman KR Moncol', 3, 3),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat Nusantara: Putri Sindang Bulan', 'Shendiane Rimandani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Cerita Rakyat Nusantara: Sultan Dhomas', 'Shendiane Rimandani', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Akal Si Kancil', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Bangau dan Kura-kura', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Beruang dan Ikan', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Gajah dan Tikus', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Kancil dan Pak Tani', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Kecerdikan Si Kancil', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Kerajaan Semut', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Perlombaan Lari', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Persahabatan Singa dan Tikus', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Rusa yang Sombong', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Si Kancil yang Cerdik', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Dongeng Binatang: Ular yang Licik', 'Endyas Wiguna', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Fabel AESOP: Semut dan Belalang', 'Shendiane Rimandani', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Anjing', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Ayam', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Burung Kaka Tua', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Gajah', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Ikan', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Katak', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Kupu-Kupu', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Lumba-Lumba', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Monyet', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Paus', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Penguin', 'M. Rantissi', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Singa', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Hewan: Zebra', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Mengenal Profesi: Masinis', 'Rae Sitha Patappa', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Adam AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Ayub AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Daud AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Harun AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Hud', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Idris AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Ilyas AS', 'Ibnu Muhiddin', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Isa AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Ishak AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Ismail AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Luth AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Muhammad SAW', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Musa AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Nuh AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Shaleh AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Sulaiman AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Syua''ib AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Yahya AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Yakub AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Yunus AS', 'Ibnu Muhiddin', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Zakaria AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Nabi-Nabi: Nabi Zulkifli AS', 'Ibnu Muhiddin', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Seri Petualangan Remaja: Sepeda Yang Hilang', 'Francine Pascal', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Si Hati Putih', 'Nadia Shafina Rahmah', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Siasat Kepiting', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Singa dan Tikus', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Star Kids', 'Aurada', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Sunatan Spesial', 'Ali Muakhir', 3, 3),
(gen_random_uuid(), 'Buku Cerita Anak', 'Superb Kuri', 'Vya Ansyah', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Gunung Monster', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Tengkorak Bersuara', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Kucing Bengkok', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Rumah Mengkerut', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Nuri Gagap', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Jeritan Jam', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Kurcaci Ajaib', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Puri Setan', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Jejak Menyala', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Trio Detektif: Misteri Tebing Menyala', 'Alfred Hitchcock', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Thalhah bin Ubaidillah: Tak Pernah Ingkar Janji', 'Anisa N. S.', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'The Cat Who Saved Books', 'Sosuke Natsukawa', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Timun Emas', 'Yudhistira Ikranegara', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Tugas Nabi dan Rasul', 'Vina Sri', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Ular', 'M. Rantissi', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Umar bin Khattab Jagoanku', 'Ulfah H.T', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Unta Binatang Tangguh Di Padang Pasir', 'Daffa Media', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Usul Sang Landak', 'Dhany Larito', 2, 2),
(gen_random_uuid(), 'Buku Cerita Anak', 'Utsman bin Affan yang Dermawan', 'Ulfah H.T', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Yuk Makan dengan Baca Basmalah', 'Luthfi Yansyah', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Yuk Berbakti Kepada Orang Tua', 'Luthfi Yansyah', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Yuk Sayangi Hewan', 'Luthfi Yansyah', 1, 1),
(gen_random_uuid(), 'Buku Cerita Anak', 'Zubair bin Awwam: Sang Penolong Rasulullah', 'Sulistya W.', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', '100 Kesalahan Wanita Dalam Merawat Tubuh', 'Dr. Aiman al-Husaini', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'A Parent''s Diary: Anakku Tamu Istimewa', 'Gita Djambek & Julaian Dewi', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Agar Anak Pandai Mengelola Uang', 'Paul W Lermitte & Jennifer Merrit', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Bagaimana Memotivasi Anak Belajar', 'Lindy Petersen', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Bagaimana Menyuapi Adik?', 'Ida S. Widayanti', 3, 3),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Dahsyatnya Otak Tengah', 'Hartono Sangkanparan', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Jalan Sehat dengan Sport Theraphy', 'dr. Michael Triangto, SPKo', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Kesehatan Keluarga 98', 'Tim Penesbit Panduan Kesehatan', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Konmari Mengubah Hidup', 'Khoirun Nimah', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Kudidik Diriku Demi Mendidik Anak-Anakku', 'Toge Aprilianto', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Letter to Karel', 'Nazrul Anwar', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Melesatkan Kecerdasan Anak Dengan Kecerdasan JIwa', 'Muhammad Muhyidin', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Melihat Aura', 'Mark Smith', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Memahami Gejolak Emosi', 'Bani Garaiyan W.', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Membesarkan Anak Menjadi Manusia Yang Penuh Cinta', 'Juliska Gracinia', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Mendidik Anak Tanpa Teriakan & Bentakan', 'Ayah Edy', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Mengasah Otak Dalam Praktek Sehari-hari', 'Lawrence C. Katz, Ph.D & Manning Rubin', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'No Glasses', 'Roberto Kaplan, O.D., M.Ed.', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Osteoporosis', 'Felecia Gosman', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Panduan Vegan', 'Tim Asosiasi International Maha Guru Ching Hai', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Penyembuhan yang Dapat Dilakukan Sendiri: Pijat Refleksi', 'Gatot M. Sahid & M.B Rahimsyah AR', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Satu Atap Lima Madrasah', 'Kiki Barkiah', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Sehat Sampai Usia 90 Tahun', 'Zaenuddin HM', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Seni Memahami Balita', 'Kompas Gramedia', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Sirkuit Otak', 'dr. Arman Yusriandi', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Terapi Enzim', 'Hiromi Shinya, MD', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'The New Fat-Loss Not Weight-Loss: Gemuk Tapi Ramping', 'dr. Phaidon L. Toruan, MM', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Tidak Bisa Menyusui? Jangan Panik!', 'Gema Indonesia Menyusui', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Tubuh Sehat, Giginya?', 'drg. Pramono Rendro Pangarso, M. Kes.', 1, 1),
(gen_random_uuid(), 'Keluarga & Kesehatan', 'Why Men Die First', 'Marianne J.', 1, 1),
(gen_random_uuid(), 'Keterampilan', '20 peluang Bisnis Makanan', 'Agromedia', 1, 1),
(gen_random_uuid(), 'Keterampilan', '38 Resep Penggugah Selera Makan anak', 'Kompas Gramedia', 1, 1),
(gen_random_uuid(), 'Keterampilan', '5 Rahasia Sukses Bisnis Restoran', 'Adith Raharjo', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Aquascape: Menata Taman Dalam Akuarium', 'Vincentius Yulianto', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Basic Grammar for Beginners', 'Pertiwi Ambarningrum', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Bercocok Tanam Kubis', 'S. Mulyono', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Bercocok Tanam Rambutan', 'Siti Rochani', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Bercocok Tanam Tomat', 'Rahmatia & Pipit Pitrianan', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Bertanam Kacang Tanah', 'Mashudi', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Beternak Ayam Jawa Super', 'Suparman', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Beternak Domba', 'Siti Rochani', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Boneka Mungil Dari Kain Felt', 'Emi Risna Imawati', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Budidaya Ikan Hias', 'Soestrino', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Budidaya Lele kampung dan Lele Dumbo', 'Sutrisno', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Budidaya Tanaman Anggrek', 'Siti Rochani', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Cara Praktis Mengelola Toko dan Supermarket', 'Kuswara', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Daun Ajaib', 'Lian Maryadi & Tim Ketik Buku', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Daur Ulang Limbah', 'Farida', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'English Conversation: Pelajaran Percakapan Bahasa Inggris', 'Penerbit Alfa Surabaya', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'English Grammar Comprehension', 'Drs. Binsar Sihombing & Barbara Burton', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Gemar Bertanam di Pekarangan', 'Amalia Nur Mia', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'How To Draw Animals', 'Sadao Naito', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Keterampilan dari Kertas', 'Bagas Shinugi', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Kesehatan Mengenal Apotek Hidup', 'Yogie Nugraha Aryasetia', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Mahkota Dewa', 'Nur Diyah & Firman', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Mandarin Untuk Transaksi Jual Beli', 'D. Budiman', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Membuat Anggrek Rajin Berbunga', 'Ir. Edhi Sandra, MS.', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Membuat Tanaman Cepat Berbuah', 'Singgih S.', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Memindah Kebun Ke Dapur', 'Bahrun Sodikin', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Menanam Buah Organik', 'Singgih S.', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Menanam Sayur Secara Organik', 'Singgih S.', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Mengais Rezeki dari Lamtoro', 'Masrokhah', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Mengenal Tanaman yang berkhasiat Obat', 'Sumiati Sa''adah', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Menggemukkan Sapi Potong', 'Asyari dkk.', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Palmistri: Biarkan Tangan Bicara', 'Budi Daruputra', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Peluang Usaha Tanpa Modal Besar', 'Budi Sulistyo', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Pengelolaan Pandan Menjadi Kerajinan tangan', 'Yudi Irawan', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Percakapan Bahasa Inggris Sehari hari', 'SF Habeyb', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Persiapan Membuka Usaha Kecil yang Menghasilkan', 'Erwan Nugraha', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Pesta Pasta', 'Gaya Favorit Press', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Pintar Internet Ga'' Pakai Mikir', 'Genta Wijaya', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Praktis Menguasai Tenses', 'Drs. Adi Wijaya', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Ragam Keripik Singkong Bergizi', 'Panca Anugerah Sakti', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Resep Masakan Nasional', 'Ny. Endang Suwarno & Anugwerah Surabaya', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Revisi Pedoman Budidaya Tanaman Obat Yang Baik', 'Kementerian Pertanian Dirjen Hortikultura 2016', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Seri Serasi & Gaya Berkain', 'Tini Sardadi & Amy Wirabudi', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Simfoni Rasa Nusantara', 'Superindo', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Standar Operasional Prosedur (SOP) Budidaya Jahe', 'Kementerian Pertanian Dirjen Hortikultura 2016', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Standar Operasional Prosedur (SOP) Kapulaga Kabupaten
Tasikmalaya', 'Kementerian Pertanian Dirjen Hortikultura 2016', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Sukses Memiliki Usaha Kuliner Tanpa Modal', 'Sugi Hartarti', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Sumur Resapan', 'Ahmad Said', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Terampil Menjahit Busana Tingkat Pemula', 'Husna W. & Amalia Iffat', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Ternak Ayam Petelur di Kandang baterai', 'Suparman Pedro', 1, 1),
(gen_random_uuid(), 'Keterampilan', 'Trik Menaklukkan Tes TOEFL', 'Arif Gunawan', 1, 1),
(gen_random_uuid(), 'Motivasi', '10 Ways to Stay Positive', 'Alviani Cahyanti', 1, 1),
(gen_random_uuid(), 'Motivasi', '101 Cerita Hikmat dari Negeri China', 'Lei Wei Ye', 1, 1),
(gen_random_uuid(), 'Motivasi', '16 Wisdom & Success: Classical Motivation Series 2', 'Andrie Wongso', 1, 1),
(gen_random_uuid(), 'Motivasi', '18 Wisdom & Success: Classical Motivation Series 3', 'Andrie Wongso', 1, 1),
(gen_random_uuid(), 'Motivasi', '4 Cermin Flora Rahasia Membangun - Karakter Terbaik', 'Dhony Firmansyah', 1, 1),
(gen_random_uuid(), 'Motivasi', '7 Kebiasaan Remaja yang Sangat Efektif', 'Jack Canfiled & Kimberly Kirberger', 1, 1),
(gen_random_uuid(), 'Motivasi', '77 Inspirasi dalam Meraih Tujuan Hidup', 'Fiona Wang', 1, 1),
(gen_random_uuid(), 'Motivasi', 'A Cup of Chicken Soup for the Soul', 'Jack Canfield, Mark Victor Hansen & Barry
Spilchuk', 1, 1),
(gen_random_uuid(), 'Motivasi', 'A Cup of Comfor for Breast Cancer Survivors', 'Colleen Sell', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Atomic Habits', 'James Clear', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Bagaimana Sukses Di Tempat Kerja', 'Fred Orr', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Become a Life Balance', 'Ric Giardina', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Berani Bicara Di Depan Publik: Cara Cepat Berpidato', 'Natalie Rogers', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Berbagi Hati', 'Houtman Z. Arifin', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Build The Best of Your Life', 'Hermanto Kosasih', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Catatan Pagi', 'Fitri Sudjarwadi', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Chicken Soup foR The Preteen Soul', 'Canfiled, Mark Victor Hansen, Patty Hansen,
Irene Dunlap', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Dapat Inspirasi', 'Danang Prima & Reysa Eka', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Educated: Terdidik', 'Tara Westover', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Feel The Fear and Do It Anyway: Rasakan Ketakutan Tetapi
Tetap Lakukan', 'Susan Jeffers, Ph.D.', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Growing Up Mindful', 'Cristopher Willard, Psy.D', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Grow Your Company Grow Yourself', 'Randy E. King', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Hidup Damai Tanpa Berpikir Berlebihan', 'Tsuneko Nakamura & Hiromi Okuda', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Kiat Jitu Meningkatkan Harga Diri', 'Nathaniel Branden', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Kisah Wanita Pilihan: Keteladanan Wanita Shalihah Sepanjang
Zaman', 'Tim Penulis Majalah Qudwah', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Kunci Pencerahan Seketika', 'Maha Guru Ching Hai', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Membuat Impian Menjadi Kenyataan', 'Ida Kuraeny Bestio', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Memenangkan & Memelihara Pelanggan', 'Michael LeBoeuf, Ph.D.', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Menyembuhkan dengan Humor dan kebahagian', 'Patch Adams', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Miracle of The Brain', 'Tingka Adiati', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Mudahnya Berpikir Positif', 'Saiful Anam', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Perjalanan Sakral Menuju Diri', 'DK Elrahman', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Relasi dengan Diri Sendiri', 'Antonius Atokokhi, Antonina Panca Yuni
Wulandari, Drs. Yohanes Babari', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Relasi dengan Sesama', 'Antonius Atokokhi, Antonina Panca Yuni
Wulandari, Drs. Yohanes Babari', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Responding to Stress: Mengatasi Stress', 'Dr. Tim Rogers & Fiona Graham', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Secret of The Power', 'Rhonda Byrme', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Sejenak Merenungi Diri', 'Syaikh Amin Muhamaad Jamal', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Seorang Pria Yang Melalui Duka Dengan Mencuci Piring', 'dr. Andreas Kurniawan, Sp.KJ', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Si Cacing dan Kotoran Kesayangannya', 'Ajahn Brahm', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Siapa Bilang Jadi Karyawan Nggak Bisa Kaya ?', 'Safir Senduk', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Smart Emotion: Membangun Kecerdasan Emosi', 'Anthony Dio Martin', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Terapi Menerima Diri Sendiri', 'Rahma Kusharjanti', 1, 1),
(gen_random_uuid(), 'Motivasi', 'Young On Top', 'Billy Boen', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', '200 Kisah Terindah Sepanjang Masa Dari Cina', 'Din Man', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Aku, Meps dan Beps', 'Soca Sobhita & Reda Gaudiamo', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Barbie Butterfly Island', 'Kathleen Kellie', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Bumi Manusia', 'Pramoedya Ananta Toer', 2, 2),
(gen_random_uuid(), 'Novel/Sastra', 'Burial Rites - Ritus Ritus Pemakaman', 'Hannah Kent', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Catching Fire', 'Suzanne Collins', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Cerita Bijak Untuk Mewujudkan Legenda Pribadi', 'Dewi Minangsari', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Dubliners - Orang Orang Dublin', 'James Joyce', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Foiled', 'Jane Yolen', 3, 3),
(gen_random_uuid(), 'Novel/Sastra', 'Force Of Nature', 'Jane Harper', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Gawang Merah Putih', 'FX Rudy Gunawan', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Good Son', 'Jeong You Jeong', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Here We Lie - Masa Lalu Tidak Pernah Benar Benar Berlalu', 'Paula Treick Derboard', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Hidup Begitu Indah dan Hanya itu Yang Kita Punya', 'Dea Anugerah', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Kata-Kata Mutiara', 'Kahlil Gibran', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Lagi Gelombang', 'Kahlil Gibran', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Layla Majnun', 'Nizami Ganjavi', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Maria Beetle', 'Kotaro Isaka', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Menjadi', 'Afutami', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Metamorphosa: Saatnya Untuk Mengubah & Berubah', 'D.K El Rahman', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Mocking Jay', 'Suzanne Collins', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'No Exit', 'Taylor Adams', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Nights in Rodante: Malam-Malam di Rodante', 'Nicholas Sparks', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Nyai Dasimah', 'Rahmat Ali', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Off The Record 2', 'Ria SW', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Off The Record 3', 'Ria SW', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'One Of Us Is Lying', 'Karen M Mcmanus', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Penance', 'Minato Kanae', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'People of The Book', 'Geraldine Brooks', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Reinkarnasi', 'Titie Said', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Rumah Di Mango Street', 'Sandra Cisneros', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Sang Paralambang', 'Kahlil Gibran', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Semua Ikan di Langit', 'Ziggy Z', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Sitti Nurbaya', 'Marah Rusli', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The 100-Year-Old Man Who Climbed Out of The Window And
Disappeared', 'Jonas Jonasson', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The Architecture of Love', 'Ika Natassa', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The Book Of Ikigai', 'Ken Mogi, Ph.D', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The Cat Who Saved Books', 'Sosuke Natsukawa', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The Dragon Awakening (Kebangkitan Sang Naga)', 'Valija Zinck', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The Girl Who Fell Beneath The Sea', 'Axie Oh', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The Hunger Games', 'Suzanne Collins', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The Old Man And The Sea', 'Ernest Hemingway', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The Silent Patient - Pelukis Bisu', 'Alex Michaelidies', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'The Superstar Concert', 'Poppy Bloom', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Tube', 'Soon Won-pyung', 1, 1),
(gen_random_uuid(), 'Novel/Sastra', 'Wandering', 'Helloditta', 2, 2),
(gen_random_uuid(), 'Novel/Sastra', 'Young Sherlock Holmes: Death Cloud', 'Andrew Lane', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', '30 Hari Jago Berhitung', 'Tim Rumah Oreon', 3, 3),
(gen_random_uuid(), 'Materi Pelajaran', 'Aku Anak Indonesia', 'M. Ambar Setyorini , Kunduri', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Aku Anak Mandiri: Lingkungan di Sekitarku', 'Dr. Tjitji Wartisah S.Pd, M.Pd', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Aku Senang Rekreasi', 'M. Ambar Setyorini , Kunduri', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Basic English Grammar Third Edition', 'Betty Schrampfer Azar', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Basic Phonics Practice Books', 'Tim Penulis Early Learner', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Basics Phonics', 'Tim Penulis Early Learner', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Bimbingan Tahssin dan Tajwid Al Qur''an Utsmani Anak Buku
Satu', 'Ust. Efendi Anwar', 2, 2),
(gen_random_uuid(), 'Materi Pelajaran', 'Bimbingan Tahssin dan Tajwid Al Qur''an Utsmani Anak Buku Dua', 'Ust. Efendi Anwar', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Bimbingan Tahssin dan Tajwid Al Qur''an Utsmani Anak Buku
Tiga', 'Ust. Efendi Anwar', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Buku PR Matematika', 'Tim Rumah Oreon', 3, 3),
(gen_random_uuid(), 'Materi Pelajaran', 'Careless Kah Meng', 'May Gan', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Character Education Activity Book 1', 'Tim Penerbit Pelangi Sdn. Bhd', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Comprehension Wh- Questions', 'Educational', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Everything You Need To Know', 'Oei Chay Hoon', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Fun to Learn Preschool Workbook: Learning Numbers & Pre-
Math Skills', 'Golden Book Publishing', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Fun to Learn Preschool Workbook: Pre-Reading & Pre-Writing
Skills', 'Golden Book Publishing', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Grandpa''s Stories', 'Mohanbai S. Patel', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Handwritting Practice Writing Book', 'Tim Penulis Early Learner', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Integrated Programme', 'Oei Chay Hoon', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'IQ Starter: Enriching Children Minds Ages 3-5', 'Tim Penerbit Pelangi Sdn. Bhd', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Juara OSN: Ilmu Pengetahuan Alam SD/MI', 'Lingkar Media', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Juara OSN: Matematika SD/MI', 'Lingkar Media', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Kindergarten Mathematics 1A', 'Oei Chay Hoon', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Kindergarten Mathematics 1B', 'Markodoo P, B.Eng & Vicnesh Kumar', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Kindergarten Mathematics 1C', 'Oei Chay Hoon', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Kindergarten Mathematics 1D', 'Markodoo P B Eng', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Kuasai Tuntas Sains SD', 'Suwarno Utomo, Sutrisno Miarjo', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Learn Practise Phonics', 'Tim Green Tree Publication', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Learning Park Character Education Activity Book 4', 'Tim Penerbit Pelangi Sdn. Bhd', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Learning Together Mathematics Kindergarten 2 - Term 1', 'Child Education Co Ptd, Ltd', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Learning Together Mathematics Kindergarten 2 - Term 3', 'Child Education Co Ptd, Ltd', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Learning Together Nursery 1', 'Chua Hui Ling, M. Ed.', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Learning Together Nursery 2', 'Chua Hui Ling, M. Ed.', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Learning Together Nursery 3', 'Chua Hui Ling, M. Ed.', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Learning Together Nursery 4', 'Chua Hui Ling, M. Ed.', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Managing Time Wisely', 'Tim Penerbit Early Learner Sdn Bhd', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Mathematics', 'Early Learner Publication', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Mau Ngaji Al-Quran & Islamic Learning Center', 'Ust. Efendi Anwar', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Merawat Ciptaan Allah', 'Dr. Rina Raflesian, M.A', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Nursery Activity Book 3', 'Longman', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Nursery Activity Book 4', 'Longman', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Nursery English 1', 'Tim Penerbit Pelangi Sdn. Bhd', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Picture Sorting for Phonemic Awareness', 'Nancy Jolson Leber', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Preparing for Primary One', 'Geetha Menon, B.A PGDE', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Pre-School Vocabulary Activity Birds', 'Arowana Research & Developmental Unit', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Pre-School Vocabulary Activity Clothing', 'Arowana Research & Developmental Unit', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Pre-School Vocabulary Activity Food', 'Arowana Research & Developmental Unit', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Pre-School Vocabulary Activity Fruits', 'Arowana Research & Developmental Unit', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Pre-School Vocabulary Activity Sea Animals', 'Arowana Research & Developmental Unit', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Pre-School Vocabulary Activity Tools and Utensils', 'Arowana Research & Developmental Unit', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Pre-School Vocabulary Activity Transport Occupation', 'Arowana Research & Developmental Unit', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Pre-School Vocabulary Activity Wild Animals', 'Arowana Research & Developmental Unit', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Proyek Penguatan Profil Pelajar Pancasila', 'Dr. Tjitji Wartisah S.Pd, M.Pd', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Sight Word', 'Tim Penerbit Sterling', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Smart Learner''s Kindergarten: English', 'Edukid Distributor Sdn. Bhd.', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Sukses Meningkatkan Keterampilan Membaca', 'Aminudin', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Super Lengkap Rumus SD', 'Riptina Pawestri', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Super Lengkap Rumus SMP', 'Tim Genius', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'Terampil Berbahasa', 'Tim Rumah Oreon', 3, 3),
(gen_random_uuid(), 'Materi Pelajaran', 'Ujian Sekolah SD/MI 2024', 'Tim Master Bina Indonesia A+', 1, 1),
(gen_random_uuid(), 'Materi Pelajaran', 'UTBK SNBT 2025', 'Tim Master Tutor SNBT', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', '1 Detik: Tahukah Kalian, Apa Yang Terjadi Di Dunia Setiap Detik?', 'Tethy Ezokanzo', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Bisa Bercerita Tentang Hewan Di Sekitarku', 'Tim Anaksaleh Pratama', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Bisa Bercerita Tentang Lingkungan dan Duniaku', 'Tim Anaksaleh Pratama', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Bisa Bercerita Tentang Transportasi', 'Tim Anaksaleh Pratama', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Bisa Bercerita Tentang Tubuhku yang Sehat', 'Tim Anaksaleh Pratama', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Bisa Mengerjakan Shalat', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Makin Tahu Tentang Asteroid, Meteor, Bintang dan Galaksi', 'Anna Martina', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Makin Tahu Tentang Bumi dan Iklimnya', 'Pustaka Lebah', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Makin Tahu Tentang Planet Merkurius, Venus dan Mars', 'Anna Martina', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Tahu Jenis-Jenis Sayuran', 'Daffa Media', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Tahu Jenis-Jenis Transportasi', 'Iin Indarti', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Tahu Nama-Nama Ovipar, Binatang Bertelur', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Aku Tahu Nama-Nama Profesi', 'Dhany Larito', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Angin', 'Armandelta', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Animal World', 'Kak Kiki', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Bencana di Alam', 'Tim Armandelta Selaras', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Bencana Di Lingkungan', 'Armandelta', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Buku Pintar Atlas Indonesia & Dunia', 'Tim Penerbit Lingkar Media', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Buku Pintar Belajar', 'Drs. R Sutoyo Bakir', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Buku Pintar Matematika', 'Moh Kusnadi Wasrie', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Bumi dan Alam Semesta', 'Haditiya K.', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Cahaya dan Warna', 'Tim Bina Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Candi-Candi di Indonesia', 'Arief Hidayatullah', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Cara Jodi Menolak Narkoba', 'Bambang Trim', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Cita-Cita Menjadi Pilot', 'Precillia Agustina', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Dunia Pengetahuan yang Meragukan', 'Glorier International', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Energi Elektromagnet', 'Tim Bina Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Energi Gerak', 'Tim Bina Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Energi Listrik Statis', 'Tim Bina Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Energi Magnet', 'Tim Bina Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia 4D: Dunia Tumbuhan', 'Tim Gramedia Pustaka Utama', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Anak Hebat: Negara', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Anak Hebat: Tubuh Kita', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Cilik: Panca Indra', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Favoritku: Penemuan', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Junior: Kesenian', 'Diah Kartini Lasman, Putri Sastra, Yanyan Wijaya', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Junior: Luar Angkasa', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Junior: Pekerjaan', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Pertamaku: Ayo Lindungi Bumi Kita', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Alam Nusantara', 'Aep Saefulloh', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Anak Anak Di Dunia', 'Nicola Edwards & Andrea Stegmaier', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Cerdas Pahlawan Indonesia', 'Amazing dkk.', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Budaya Bangsa', 'Aep Saefulloh', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Kebangkitan Nasional', 'Aep Saefulloh', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Kemerdekaan RI', 'Aep Saefulloh', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Kerajaan Nusantara', 'Aep Saefulloh', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Koperasi dan Sejarahnya', 'Jam''ah Khalid', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Lembaga Negara RI Pascareformasi', 'Aep Saefulloh', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Pemimpin Bangsa dan Negara Indonesia', 'Aep Saefulloh', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Peninggalan Sejarah', 'R. Suryagung S. P.', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia IPS:  Uang dan Sejarahnya', 'Emilya Rahmat', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Mini: Alat Musik Indonesia', 'Tiga Ananda', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Pengetahuan Umum: Listrik', 'Noer Aida D Hidayat', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Pengetahuan Umum: Cahaya dan Sifat Sifatnya', 'Yoni Yuniarto', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Rumah Adat Indonesia', 'Monica Herlina', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ensiklopedia Sejarah dan Budaya', 'Tim Penerbit Lentera Abadi', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Gempa', 'Armandelta', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Gempa Bumi', 'Rahmat Margajaya', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Jarimatika', 'Trivia Astuti', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kamus 3 Bahasa', 'Muhammad Ilyas', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kamus Bergambar Untuk Anak-Anak', 'Dr. Emalia Iragailiati Sukarmi', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kamus Bergambar untuk Anak Pintar', 'Alfi Arifian & Arif', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kamus Pelajar Matematika', 'Diah Rahmatia & Pipot Pitriana', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kebakaran', 'Armadela', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kebakaran', 'Dinas Penanggulangan Kebakaran dan
Penyelamatan Prov DKI Jakarta', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kelembaban dan Gesekan', 'Tim Bina Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kenali Pancaindramu', 'Hanifah Wijaya', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kerajaan Nusantara', 'Anah Elhisani, Lina Marlina & Idatul Fitri', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Keseimbangan', 'Tim Bina Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Keselamatan Sehari-hari', 'Amirudin El Klateny', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Komik 50+ Hewan dan Tumbuhan Paling WOW Sedunia', 'Tethy Ezokanzo', 2, 2),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kreasi Ilmuwan Cilik: Seri Benda dan Sifatnya', 'Dinda Mahariesti', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kreasi Ilmuwan Cilik: Seri Hewan', 'Dinda Mahariesti', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kreasi Ilmuwan Cilik: Seri Lingkungan', 'Dinda Mahariesti', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kreasi Ilmuwan Cilik: Seri Tata Surya', 'Dinda Mahariesti', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kreasi Ilmuwan Cilik: Seri Tubuh Manusia', 'Dinda Mahariesti', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Kreasi Ilmuwan Cilik: Seri Tumbuhan', 'Dinda Mahariesti', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Laut dan Habitatnya', 'Tim Armandelta Selaras', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Laut dan Pelestariannya', 'Tim Armandelta Selaras', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Laut dan Pencemarannya', 'Tim Armandelta Selaras', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Lebih Dekat Dengan Bumiku 1', 'David Burner', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Lebih Dekat Dengan Bumiku 2', 'David Burner', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Lebih Dekat Dengan Bumiku 3', 'David Burner', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Lebih Dekat Dengan Lautku 1', 'Martyn Bramwell', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Lebih Dekat Dengan Lautku 2', 'Martyn Bramwell', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Lebih Dekat Dengan Lautku 3', 'Martyn Bramwell', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Lift the Flap Anak Cerdas: Tubuh Manusia', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Lingkungan di Sekitarku', 'Tim Armandelta Selaras', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Lingkungan Sehat', 'Sulinah', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Makanan Kesukaan', 'Daffa Media', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Matematika 1', 'David Glover', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Matematika 2', 'David Glover', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Matematika 3', 'David Glover', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Meneladani Manusia Pilihan Allah: Masyarakat Jahiliyah', 'Pustaka Lebah', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Mengapa Ada Air Mata Di Dunia?', 'Arleen Amidjaja', 3, 3),
(gen_random_uuid(), 'Pengetahuan Anak', 'Mengenal Terumbu Karang', 'Cepi Heryadi', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Molekol', 'Tim Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Nasi yang Tidak Ingin Dibuang', 'Nia Apriliah', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Pencemaran Linkungan', 'Tim Armandelta Selaras', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Penemuan Kamera', 'PT Elex Media Komputindo', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Pengetahuan Menjadi Presiden', 'Valerie Wyatt', 3, 3),
(gen_random_uuid(), 'Pengetahuan Anak', 'Pengetahuan Tentang Udara', 'Dewi Yulianan Astuti', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Permainan Tradisional Anak Negeri', 'BUMN', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Pesawat Sederhana', 'Tim Bina Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Polikultur Ikan Laut', 'Alfian Sitranggang', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Ragam Permainan Tradisional di Indonesia', 'Kak Aifa', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'RPUL dan RPAL', 'PT. Bintang Indonesia Jakarta', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Sejarah Batik Indonesia', 'Deden Dedi S', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seni Geografi dan Alam Semesta 1', 'Dick Bateman', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seni Geografi dan Alam Semesta 2', 'Dick Bateman', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seni Geografi dan Alam Semesta 3', 'Dick Bateman', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seni Grafis Yang Fantastis', 'Izzudin Irsan Mujib & Arief Kurniawan', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Serangga Super', 'Kyowon Editorial', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seri IPA dan Teknologi: Air', 'M Zaki Ramadhani', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seri IPA dan Teknologi: Dalam Kehidupan', 'M Algibran', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seri IPA dan Teknologi: Gerak dan Energi', 'Ramlan Firmansayh', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seri IPA dan Teknologi: Transportasi', 'Alya Sukmaputri', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seri IPA dan Teknologi: Tubuh dan Manusia', 'Wahyu Danuwirya', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seri IPA dan Teknologi: Udara dan Lingkungan', 'Endah Kusumardani', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seri Mengenal Teknologi Dasar A-Z 1', 'Robin Kerrod', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seri Mengenal Teknologi Dasar A-Z 2', 'Robin Kerrod', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Seri Mengenal Teknologi dasar Teknologi A-Z 3', 'Robin Kerrod', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Sharks', 'Ben Grossblat', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Si Penjaga Pulau Komodo', 'Kenny Dewi', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'SIGAP RPAL', 'Eka Purnama M., Nur Annisa, Irma Indriyani, Ika
Fajar', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'SIGAP RPUL', 'Rofi''ah Nurhayati, Umu Fatimiah, Rohmiati,
Nikotiana H.J.', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Siklus Kehidupan di Alam', 'Baiduri Widad', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Suara, Udara dan Bunyi', 'Tim Bina Sumber Daya MIPA', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Tanya Jawab Seru Tantang Tata Surya', 'Ian Graham', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Tanya Jawab Seru Tentang Planet Kita', 'Camilla De La Bedoyere', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Tata Surya dan Penjelajahan Ruang Angkasa', 'Drajat', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Tsunami', 'Armadela', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Tubuh Manusia 1', 'Bridget & Neil Ardley', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Tubuh Manusia 2', 'Bridget & Neil Ardley', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Tubuh Manusia 3', 'Bridget & Neil Ardley', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Waktu, Panjang dan Berat', 'Emma Saidah Zhafira', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Water', 'Pustaka Lebah', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'World History Medieval World', 'Pustaka Lebah', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'World History Renaissance Era', 'Pustaka Lebah', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'World History Water', 'Pustaka Lebah', 1, 1),
(gen_random_uuid(), 'Pengetahuan Anak', 'Yuk Mengintip Bumi', 'PT. Elex Media Komputindo', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Aktivitas Edukatif PAUD: Jam dan Waktu', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Bermain Bersama Di Peternakan', 'Nina Filipek', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Bermain Bersama di Rumah', 'Nina Filipek', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Bermain Bersama di Taman', 'Nina Filipek', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Buku Cermin Balita: Lihat, Akulah Singa', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Buku Interaktif Silikon: Belajar Kata dan Warna', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'First Words Felt Book: Around Me (Sekitarku)', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Jago Membaca A I U E O', 'Ibu Ninin', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Pop Up Book: A, B, C untuk Balita', 'Noo H. Dee & Faza', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Pop Up Book: Belajar dan Bermain 1, 2, 3', 'Omega Hanifa', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Seri Buku PAUD/TK: Mengenal Angka 1 - 20', 'Aida Fitria', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Seri Buku PAUD/TK: Mengenal Huruf A - Z', 'Aida Fitria', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Seri Buku PAUD/TK: Mengenal Warna dan Bentuk', 'Aida Fitria', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Seri PAUD Pintar: My First Book of Everything', 'Award Publications LImited', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'Tanaman Di Sekitarku', 'Erlangga KIds', 1, 1),
(gen_random_uuid(), 'Pra-Sekolah', 'The Rainbow School', 'Nuha', 1, 1),
(gen_random_uuid(), 'Referensi', '6000 Tahun Sang Merah Putih', 'Prof. H. Muhammad Yamin', 1, 1),
(gen_random_uuid(), 'Referensi', 'A Man Called #AHOK', 'Rudi Valinka', 1, 1),
(gen_random_uuid(), 'Referensi', 'Albert Einsten', 'Penerbit PT Elex Media', 1, 1),
(gen_random_uuid(), 'Referensi', 'Atlas Global Raya', 'CV Pustaka Agung Harapan', 1, 1),
(gen_random_uuid(), 'Referensi', 'Atlas Indonesia dan Dunia', 'Dian Rakyat', 1, 1),
(gen_random_uuid(), 'Referensi', 'Baca, Tulis, Hitung', 'Lutfiatni Lathifah, M.Pd', 1, 1),
(gen_random_uuid(), 'Referensi', 'Bersatu untuk Indonesia', 'Desy Arisandy & Idatul Fitri', 1, 1),
(gen_random_uuid(), 'Referensi', 'Bertaruh Nyawa Merajut Damai: Kisah Gerakan Peringatan Dini
Konflik di Ambon', 'Bambang Wisudo', 1, 1),
(gen_random_uuid(), 'Referensi', 'Buku Babon Sejarah Dunia', 'H Kenzou Alvarendra', 1, 1),
(gen_random_uuid(), 'Referensi', 'Buku Pintar Atlas Indonesia & Dunia', 'Lingkar Media', 1, 1),
(gen_random_uuid(), 'Referensi', 'Bumi dan Ruang Angkasa', 'Prof. Dr. Wahyudin M.Pd', 1, 1),
(gen_random_uuid(), 'Referensi', 'Dunia Hewan dan Tumbuhan', 'Prof. Dr. Wahyudin M.Pd', 1, 1),
(gen_random_uuid(), 'Referensi', 'English for Children: Grammar and Conversation', 'Sam S. Warib', 1, 1),
(gen_random_uuid(), 'Referensi', 'EYD - Ejaan Yang Disempurnakan', 'Ernawati Waridah', 1, 1),
(gen_random_uuid(), 'Referensi', 'Gunung', 'Pustaka Alam', 1, 1),
(gen_random_uuid(), 'Referensi', 'Habibie dan Ainun', 'Bacharuddin Jusuf Habibie', 1, 1),
(gen_random_uuid(), 'Referensi', 'Insinyur', 'Pustaka Ilmu', 1, 1),
(gen_random_uuid(), 'Referensi', 'Justin Bieber: Never Say Never', 'Imran Laha', 2, 2),
(gen_random_uuid(), 'Referensi', 'Kamus Bahasa Indonesia - Jawa Kuno', 'Pusat Bahasa Kementerian Pendidikan Nasional', 1, 1),
(gen_random_uuid(), 'Referensi', 'Kamus Indonesia-Inggris', 'John U. Wolff', 1, 1),
(gen_random_uuid(), 'Referensi', 'Kamus Inggris-Indonesia', 'John M. Echols', 1, 1),
(gen_random_uuid(), 'Referensi', 'Kamus Lengkap Bahasa Indonesia', 'DRa Sulistyowati', 1, 1),
(gen_random_uuid(), 'Referensi', 'Kamus Lengkap Indonesia - Inggris', 'Alan M. Stevens & A. Ed. Schmidgall-Tellings', 1, 1),
(gen_random_uuid(), 'Referensi', 'Kamus Lengkap Inggris- Indonesia 1 Milliar', 'Tim Penerbit Surabaya', 1, 1),
(gen_random_uuid(), 'Referensi', 'Kamus Saku Bahasa Indonesia', 'Tim B First', 1, 1),
(gen_random_uuid(), 'Referensi', 'Kesehatan dan Penyakit', 'Pustaka Ilmu', 1, 1),
(gen_random_uuid(), 'Referensi', 'Ki Hajar Dewantara: Bapak Pendidikan Indonesia', 'Frida Firdiani', 1, 1),
(gen_random_uuid(), 'Referensi', 'Kiai Penggerak: Novel Biografi K.H. Ahmad Dahlan', 'Haidar Musyafa', 1, 1),
(gen_random_uuid(), 'Referensi', 'Kya-Kya Bareng Koh Dahlan Iskan: Menapak Tilas Derap Langkah
Pluralisme Dahlan Iskan', 'Freddy H. Istanto', 1, 1),
(gen_random_uuid(), 'Referensi', 'Laut', 'Pustaka Alam', 1, 1),
(gen_random_uuid(), 'Referensi', 'Lionel Messi vs Christiano Ronaldo', 'Irfan Hasuki', 3, 3),
(gen_random_uuid(), 'Referensi', 'Maher Zain: Cinta Dari Timur', 'Nunik Utami & Anom Triwiyanto', 2, 2),
(gen_random_uuid(), 'Referensi', 'Makanan dan Gizi', 'Pustaka Ilmu', 1, 1),
(gen_random_uuid(), 'Referensi', 'Mamalia', 'Pustaka Alam', 1, 1),
(gen_random_uuid(), 'Referensi', 'Mata Air Keteladanan: Pancasila Dalam Perbuatan', 'Yudi Latif', 1, 1),
(gen_random_uuid(), 'Referensi', 'Mohammad Hatta: Hidup Jujur dan Sederhana Untuk Indonesia', 'Anom Whani Wicaksana', 1, 1),
(gen_random_uuid(), 'Referensi', 'Pedoman Resmi PUEBI Terbaru', 'Tim Tentor Oxygen', 1, 1),
(gen_random_uuid(), 'Referensi', 'Pencemaran Desa', 'Hadi Permana', 1, 1),
(gen_random_uuid(), 'Referensi', 'Perempuan Menjunjung Separuh Langit', 'Nicholas D. Kristof & Sheryl WuDunn', 1, 1),
(gen_random_uuid(), 'Referensi', 'Perilaku Binatang', 'Pustaka Alam', 1, 1),
(gen_random_uuid(), 'Referensi', 'Planet', 'Pustaka Ilmu', 1, 1),
(gen_random_uuid(), 'Referensi', 'Regulasi Berkendara', 'Korps Lalu Lintas POLRI', 1, 1),
(gen_random_uuid(), 'Referensi', 'Sarung Jokowi dan Wak, Wak, Wak', 'J. Osdar', 1, 1),
(gen_random_uuid(), 'Referensi', 'Seni Budaya dan Warisan Indonesia', 'PT. Aku Bisa Jakarta', 1, 1),
(gen_random_uuid(), 'Referensi', 'Steve Jobs: iCon Apple', 'Hendri F. Isnaeni', 2, 2),
(gen_random_uuid(), 'Referensi', 'Tesaurus Plus Indonesia - Inggris', 'Arif Mansur Makmur', 1, 1),
(gen_random_uuid(), 'Referensi', 'The Life of Katy Perry', 'Dewi Rieka', 2, 2),
(gen_random_uuid(), 'Referensi', 'Titik Nol: Makna Sebuah Perjalanan', 'Agustinus Wibowo', 1, 1),
(gen_random_uuid(), 'Referensi', 'Tubuh', 'Pustaka ilmu', 1, 1),
(gen_random_uuid(), 'Referensi', 'Undang-Undang Perseroan Terbatas: UU No. 1/1995', 'Penerbit Sinar Grafika', 1, 1),
(gen_random_uuid(), 'Referensi', 'UUD 1945 dan Perubahannya + Struktur Ketatanegaraan', 'Redaksi Indonesia Tera', 1, 1),
(gen_random_uuid(), 'Referensi', 'UUD 1945 untuk pelajar dan umum', 'Tim Redaksi BIP', 1, 1),
(gen_random_uuid(), 'Referensi', 'Visual Ilmu dan Pengetahuan Populer Memahami Alam Semesta', 'Nathalie F & Calude L', 1, 1),
(gen_random_uuid(), 'Referensi', 'Visual Ilmu dan Pengetahuan Populer Memahami Iklim dan
Lingkungan', 'Stephane Batigne, Josee B., Nathalie F.,
Agence S.', 1, 1),
(gen_random_uuid(), 'Referensi', 'Visual Ilmu dan Pengetahuan Populer Memahami Keragaman
Tumbuhan', 'Gilles Veniza', 1, 1),
(gen_random_uuid(), 'Referensi', 'Visual Ilmu dan Pengetahuan Populer Memahami Planet Bumi', 'Stephane Batigne, Josee B., Nathalie F.,
Agence S. & Claude L.', 1, 1),
(gen_random_uuid(), 'Referensi', 'Visual Ilmu dan Pengerahuan Populer Mengenal Tubuh Manusia', 'Stephane Batigne, Josee B. & Nathalie F.', 1, 1),
(gen_random_uuid(), 'Umum', '100 Kisah Klasik Pemasaran', 'Jacky Mussry, Waizly Darwin & Edwin Hardi', 1, 1),
(gen_random_uuid(), 'Umum', '5 Keberanian yang Dimiliki Orang-Orang Sukses', 'Komarudin Chalil', 1, 1),
(gen_random_uuid(), 'Umum', '52 Tip & Trik Sales', 'Dodi Mawardi', 1, 1),
(gen_random_uuid(), 'Umum', 'A Child Called It', 'Dave Pelzer', 1, 1),
(gen_random_uuid(), 'Umum', 'Begini Begitu Insan Gemini', 'Aji Marto', 1, 1),
(gen_random_uuid(), 'Umum', 'Buku Pintar Feng Shui', 'Victoria Hua Wongsengtian', 1, 1),
(gen_random_uuid(), 'Umum', 'Chinese Antrology: Temukan Shio Anda dan Simak Pengaruhnya', 'Sabrina Liao', 1, 1),
(gen_random_uuid(), 'Umum', 'Ekowisata Berwawasan Lingkungan Hidup', 'Drs. H. Oka A Yoeti, MBA', 1, 1),
(gen_random_uuid(), 'Umum', 'Ekowisata dan Pembangunan Berkelanjutan', 'Iwan Nugroho', 1, 1),
(gen_random_uuid(), 'Umum', 'Ekowisata, Konsepsi, Penerapan dan Strataegi Pengembangan
Pariwisata Indonesia', 'Mohammad Hamsal', 1, 1),
(gen_random_uuid(), 'Umum', 'Encyclopedia of Space', 'David Hughes & Robin Kerrod', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Agama & Seksualitas', 'Gadis Arivia, Ratna Syafrda, Asikin Arif, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Agensi Perempuan Pedesaan 1', 'Gadis Arivia, Mariana Amiruddin, M.Hum,, Prof.
Dr. Sulistyowati, Ratna Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Agensi Perempuan Pedesaan 2', 'Gadis Arivia, Prof. Dr. Sulistyowati, Ratna
Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Berantas Korupsi', 'Dr. Gadis Arivia, Ratna Syafrida Dhanny', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Budaya, Tradisi, Adat', 'Gadis Arivia, Mariana Amiruddin, M.Hum,, Prof.
Dr. Sulistyowati, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Feminisme dan Cinta', 'Andi Misbahul Pratiwi, Naufaludin Ismail, Bella
Sandiata', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Gender dan Teknologi', 'Gadis Arivia, Ratna Syafrda, Asikin Arif, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Hak Anak dan Keadilan Gender', 'Gadis Arivia, Prof. Dr. Sulistyowati, Ratna
Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Invisible & Unprotected', 'Mariana Amiruddin, David Huise, David Hulse,
dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Karier dan Rumah Tangga', 'Dr. Gadis Arivia, Prof Dr. Sulistyowati Irianto, Dr. Phil Dewi Cahyaningrum, Dr. Soe Tjen Marching', 2, 2),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Pemikiran dan Gerakan Perempuan
Indonesia', 'Gadis Arivia, Prof. Dr. Sulistyowati, Ratna
Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Pemili dan Keterwakilan', 'Gadis Arivia, Ratna Syafrda, Asikin Arif, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Pemilu, Agama & Status Perempuan', 'Gadis Arivia, Prof. Dr. Sulistyowati, Ratna
Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Perempuan dalam Kabinet', 'Gadis Arivia, Prof. Dr. Sulistyowati, Ratna
Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Perempuan dan Lahan Gambut', 'Gadis Arivia, Prof. Dr. Sulistyowati, Ratna
Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Perempuan dan Pandemi Covid-19', 'Gadis Arivia, Prof. Dr. Sulistyowati, Ratna
Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Perempuan lansia', 'Gadis Arivia, Nur Iman Subono, Adriani Venny,
Ida Danny, Asikin Arif', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Perempuan Politisi', 'Gadis Arivia, Mariana Amiruddin, M.Hum,, Prof.
Dr. Sulistyowati, Ratna Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Sekolah Mahal', 'Kiki Febriyanti, Juliana, Shera Rindra
Pringgodigdo, DonnyAnggoro', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: SHSR (Sexual & Reproductive Health &
Rights) & Perubahan Iklim', 'Dr. Gadis Arivia, Prof. Dr. Sulistyowati Irianto,
Ratna Syafrida Dhanny', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Status Perempuan dalam STEM', 'Gadis Arivia, Prof. Dr. Sulistyowati, Ratna
Syafrda, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Perempuan: Tubuh Perempuan dalam Ekologi', 'Gadis Arivia, Ratna Syafrda, Asikin Arif, dkk.', 1, 1),
(gen_random_uuid(), 'Umum', 'Jurnal Sosiologi Masyarakat', 'Tim Penulis LabSosio', 2, 2),
(gen_random_uuid(), 'Umum', 'Jurus Pintar Kartunis', 'Nasim Halim', 1, 1),
(gen_random_uuid(), 'Umum', 'Kamus Ideal Inggris - Indonesia Bergambar: Grammar and
Conversation', 'Drs. P. Handoko', 1, 1),
(gen_random_uuid(), 'Umum', 'Kamus Lengkap Inggris- Indonesia', 'Penerbit Mahkota Kita', 1, 1),
(gen_random_uuid(), 'Umum', 'Kebenaran, Pluraisme, dan Kehidupan Publik', 'Os Guinness, Ph.D, Pdt. Dr. Stephen Tong,     Dr.
Muhammad As Hikam', 1, 1),
(gen_random_uuid(), 'Umum', 'Kisah Merah Putih', 'Panitian Peringatan Hari Kemerdekaan 2017', 2, 2),
(gen_random_uuid(), 'Umum', 'Kisah Teladan 25 Nabi dan Rasul', 'MB. Rahimsyah', 1, 1),
(gen_random_uuid(), 'Umum', 'Kitab Kumpulan Lagu Anak Indonesia Super', 'Nada Irama', 1, 1),
(gen_random_uuid(), 'Umum', 'Komik Pancasila: Cinta RI Bareng Bang Panca dan Nona Sila', 'Immalevav & W. B. Atmoko', 1, 1),
(gen_random_uuid(), 'Umum', 'Let''s Change: Kepemimpinan, Keberanian dan Perubahan', 'Rhenald Kasali', 1, 1),
(gen_random_uuid(), 'Umum', 'Listen Aja Gak Tahu', 'Robert L. Wolke', 1, 1),
(gen_random_uuid(), 'Umum', 'Mengapa Harus Kerja Keras Kalau Santai Saja Bisa Sukses?', 'Ernie J. Zelinski', 1, 1),
(gen_random_uuid(), 'Umum', 'Nyanyian Negeriku: Kumpulan Lagu Wajib Nasional & Daerah', '', 1, 1),
(gen_random_uuid(), 'Umum', 'Obsessive Corbuzier''s Diet', 'Deddy Corbuzier', 1, 1),
(gen_random_uuid(), 'Umum', 'Pemgembangan Pariwisata Berkelanjutan Melalui Ekowisata', 'RA Amalia Yunita', 1, 1),
(gen_random_uuid(), 'Umum', 'Pengelolaan Ekowisata Desa', 'Hayat, Muhammad Ama Ridlwan, Slamet
MUchsin', 1, 1),
(gen_random_uuid(), 'Umum', 'Perencanaan Ekowisata Dari Teori Ke Aplikasi', 'Janianton Damanik & Helmut F Weber', 1, 1),
(gen_random_uuid(), 'Umum', 'Perencanaan Pengembangan Daerah Tujuan Pariwisata', 'Mohamad Ridwan, ST.M.Sc &
Dr. Windra Aini, M.M', 1, 1),
(gen_random_uuid(), 'Umum', 'Rekreasi Alam dan Ekowisata', 'Eks, Haraini Muntasib, Eva Rachmawati, Resti
Meilani, Ani Mardiastuti, Siti Badriyah
Rushayati, Arzyanan Sunkar, Nandi Kosmaryandi', 1, 1),
(gen_random_uuid(), 'Umum', 'Resep Kaya Ala Tionghoa: Financial Strategy', 'Lie Charlie', 1, 1),
(gen_random_uuid(), 'Umum', 'Restorasi Parlemen', 'Viktor B Laiskodat', 1, 1),
(gen_random_uuid(), 'Umum', 'Rumah di Tanah Rempah', 'Nurdiyansah Dalidjo', 1, 1),
(gen_random_uuid(), 'Umum', 'Selalu Ada Peluang', 'Jackie Ambadar, Miranty Abidin & Yanty Isa', 1, 1),
(gen_random_uuid(), 'Umum', 'Seni Menguasai Copywriting Persuasif', 'Febri Asiani', 1, 1),
(gen_random_uuid(), 'Umum', 'Siapa Orang Asli Palestina?', 'Zafarul Islam Khan, Ph.D.', 1, 1),
(gen_random_uuid(), 'Umum', 'Simplify Your Working Life: Bekerja Cerdas dan Efektif', 'Fergus O''Connell', 1, 1),
(gen_random_uuid(), 'Umum', 'Super Junior in Comic: 50+ Joke Seru Ala Super Junior', 'Merri An', 2, 2),
(gen_random_uuid(), 'Umum', 'Surat Terbuka Untuk 12 Tokoh Besar Dunia', 'Max Eastman', 1, 1),
(gen_random_uuid(), 'Umum', 'Surat-Surat Seorang Usahawan Kepada Putranya', 'G. Kingsley Ward', 1, 1),
(gen_random_uuid(), 'Umum', 'The 21 Irrefutable Laws of Leadership: 21 Hukum
Kepemimpinan Sejati', 'John C. Maxwell', 1, 1),
(gen_random_uuid(), 'Umum', 'The Air Asia Story', 'Sen Ze & Jane Ng', 1, 1),
(gen_random_uuid(), 'Umum', 'The Secret Anmal Minds', 'Rubi Gou & Angelica Kwee', 1, 1),
(gen_random_uuid(), 'Umum', 'Wasiat Dari Tanah Surga Yang Hilang', 'H.M. Lintang Waluyo', 1, 1),
(gen_random_uuid(), 'Umum', 'We Are Super Junior', 'Chris Oetoyo', 2, 2),
(gen_random_uuid(), 'Umum', 'Winning Strategy: Strategi Efektif Merebut & Mempertahankan
Pangsa Pasar', 'Handi Irawan D., MBA. MCom.', 1, 1),
(gen_random_uuid(), 'Umum', 'Wow! 25 Formula Bisnis Teruji Dan Terpopuler', 'Tantowi Yahya & Ippho Santosa', 1, 1);